"""Provider-neutral coursework analysis over the Obsidian vault."""

from .diagnostics import (
    DiagnosticConflictError,
    DiagnosticConversation,
    DiagnosticCorrection,
    DiagnosticCorrectionOutcome,
    DiagnosticEngine,
    DiagnosticObservation,
    DiagnosticOutcome,
    DiagnosticPlan,
    DiagnosticPrompt,
    DiagnosticRequest,
    DiagnosticSubmission,
    DiagnosticValidationError,
    EvidenceKind,
    Familiarity,
    ObservationResult,
    ScriptedDiagnosticConversation,
)
from .course_archive import (
    CourseArchiveConflictError,
    CourseArchiveEngine,
    CourseArchiveError,
    CourseArchiveIntegrityError,
    CourseArchiveOutcome,
    CourseArchivePlan,
    CourseArchiveRequest,
    CourseArchiveState,
    CourseArchiveValidationError,
)
from .engine import AnalysisEngine, AnalysisRequest, AnalysisOutcome
from .link_integrity import (
    LinkIntegrityError,
    LinkIntegrityReport,
    LinkIssue,
    audit_vault_links,
)
from .knowledge import (
    KnowledgeCaptureOutcome,
    KnowledgeCaptureRequest,
    KnowledgeRefreshOutcome,
    KnowledgeRepository,
    KnowledgeRepositoryError,
)
from .providers import ModelAdapter, adapter_from_env
from .research import (
    ResearchAdapter,
    ResearchEngine,
    ResearchError,
    ResearchHit,
    ResearchOutcome,
    ResearchRequest,
    ResearchTransportError,
    ResearchUsage,
    ResearchValidationError,
    SavedJsonResearchAdapter,
    SearXNGHttpAdapter,
    build_public_concept_query,
    default_research_cache_path,
    research_adapter_from_env,
    validate_research_cache_path,
)
from .schema import AnalysisMode, AnalysisValidationError

__all__ = [
    "AnalysisEngine",
    "AnalysisMode",
    "AnalysisOutcome",
    "AnalysisRequest",
    "AnalysisValidationError",
    "CourseArchiveConflictError",
    "CourseArchiveEngine",
    "CourseArchiveError",
    "CourseArchiveIntegrityError",
    "CourseArchiveOutcome",
    "CourseArchivePlan",
    "CourseArchiveRequest",
    "CourseArchiveState",
    "CourseArchiveValidationError",
    "DiagnosticConflictError",
    "DiagnosticConversation",
    "DiagnosticCorrection",
    "DiagnosticCorrectionOutcome",
    "DiagnosticEngine",
    "DiagnosticObservation",
    "DiagnosticOutcome",
    "DiagnosticPlan",
    "DiagnosticPrompt",
    "DiagnosticRequest",
    "DiagnosticSubmission",
    "DiagnosticValidationError",
    "EvidenceKind",
    "Familiarity",
    "KnowledgeCaptureOutcome",
    "KnowledgeCaptureRequest",
    "KnowledgeRefreshOutcome",
    "KnowledgeRepository",
    "KnowledgeRepositoryError",
    "LinkIntegrityError",
    "LinkIntegrityReport",
    "LinkIssue",
    "ModelAdapter",
    "ObservationResult",
    "ResearchAdapter",
    "ResearchEngine",
    "ResearchError",
    "ResearchHit",
    "ResearchOutcome",
    "ResearchRequest",
    "ResearchTransportError",
    "ResearchUsage",
    "ResearchValidationError",
    "SavedJsonResearchAdapter",
    "SearXNGHttpAdapter",
    "ScriptedDiagnosticConversation",
    "audit_vault_links",
    "adapter_from_env",
    "build_public_concept_query",
    "default_research_cache_path",
    "research_adapter_from_env",
    "validate_research_cache_path",
]
